language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
services:
  - mysql
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - mysql -e "create database IF NOT EXISTS \`acf-migrations\`;" -uroot

install: composer update --prefer-dist

before_script:
  - ./wp-install.sh

script: composer test