language: php
php:
  - '7.1'
services:
  - mysql
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - mysql -e "create database IF NOT EXISTS acf-migrations;" -uroot

install: composer update --prefer-dist

before_script:
  - ./wp-install.sh
  - cd $TRAVIS_BUILD_DIR/tmp/wordpress
  - wp db export $TRAVIS_BUILD_DIR/tests/_data/dump.sql
  - cd $TRAVIS_BUILD_DIR

script: composer test